# Generated by Django 5.0.2 on 2025-04-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PupilDistanceMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(verbose_name='Distância Pupilar')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Nível de Confiança')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validado')),
                ('validated_distance', models.FloatField(blank=True, null=True, verbose_name='Distância Validada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Medição de Distância Pupilar',
                'verbose_name_plural': 'Medições de Distância Pupilar',
                'ordering': ['-created_at'],
            },
        ),
    ]
