# Generated by Django 5.0.2 on 2025-04-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupildistancemeasurement',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Imagem Base64'),
        ),
    ]
